name: CI/CD Pipeline

env:
  DOCKER_REGISTRY: <docker-registry-url>
  HELM_CHART_REPO: <helm-chart-repository-url>

on:
  push:
    branches:
      - main
      - develop
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: <docker-registry-url>
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t <docker-registry-url>/<image-name>:$GITHUB_SHA .
          docker push <docker-registry-url>/<image-name>:$GITHUB_SHA

  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Package Helm chart
        run: |
          helm package <path-to-helm-chart>
          curl --data-binary "@<app-name>.tgz" <helm-chart-repository-url>

  deploy-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Kubernetes using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app create
          args: <app-name>-develop --repo <git-repo-url> --path <path-to-helm-chart> --dest-server <kubernetes-server-url> --dest-namespace <kubernetes-namespace> --revision develop --skip-create
        env:
          ARGOCD_OPTS: --grpc-web

      - name: Sync application using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app sync
          args: <app-name>-develop
        env:
          ARGOCD_OPTS: --grpc-web

  deploy-stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Kubernetes using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app create
          args: <app-name>-stage --repo <git-repo-url> --path <path-to-helm-chart> --dest-server <kubernetes-server-url> --dest-namespace <kubernetes-namespace> --revision stage --skip-create
        env:
          ARGOCD_OPTS: --grpc-web
      - name: Sync application using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app sync
          args: <app-name>-stage
        env:
          ARGOCD_OPTS: --grpc-web

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Kubernetes using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app create
          args: <app-name>-production --repo <git-repo-url> --path <path-to-helm-chart> --dest-server <kubernetes-server-url> --dest-namespace <kubernetes-namespace> --revision production --skip-create
      - name: Sync application using ArgoCD
        uses: argoproj-labs/argocd-action@v3.0.0
        with:
          command: app sync
          args: <app-name>-production
        env:
          ARGOCD_OPTS: --grpc-web
